### ISSUE TITLE
Can't add new applications/new groups

### ISSUE THREAD

**Issue by mattprg** [Raffarti/Touchegg-gce#10]
Hi  @Raffarti,
when I click Add on the bottom left, the terminal shows me following error message:
QMetaObject::connectSlotsByName: No matching signal for on_NewGroupDialog_accepted()
Entering an application and clicking ok doesn't change anything.
Besides that everything works fine :).
Thanks,
Matthias

**Comment by Raffarti** [comment]
Hi @mattprg,
thanks for *signaling* that.
There was some some change left halfway, probably unsaved.
Fixed.

**Comment by mattprg** [comment]
@Raffarti 
Thanks for your quick response.
Unfortunately, the issue still remains for me.
I still receive the error message and can't add applications/groups.

**Comment by Raffarti** [comment]
@mattprg 
More testing pointed out that is a qt4 only issue, on qt5 it works.
I'm investigating it.

**Comment by Raffarti** [comment]
@mattprg 
it should work now, please test it again.

**Comment by mattprg** [comment]
@Raffarti 
It works now, thank you :)
